// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  aiComplete: (config: ModelConfig, instruction: string, context: string) =>
    __TAURI_INVOKE<string>("ai_complete", { config, instruction, context }),
  listModels: (config: ModelConfig) =>
    __TAURI_INVOKE<ModelList>("list_models", { config }),
  modelVerify: (config: ModelConfig) =>
    __TAURI_INVOKE<ModelVerification>("model_verify", { config }),
  comfyRequest: (
    baseUrl: string,
    workflow: string | null,
    promptId: string | null,
  ) => __TAURI_INVOKE<string>("comfy_request", { baseUrl, workflow, promptId }),
  libraryLoad: () => __TAURI_INVOKE<Library>("library_load"),
  librarySave: (docs: Document[], expectedRevision: number) =>
    __TAURI_INVOKE<number>("library_save", { docs, expectedRevision }),
  libraryHistory: (docId: string) =>
    __TAURI_INVOKE<Snapshot[]>("library_history", { docId }),
  gitInspect: (path: string) =>
    __TAURI_INVOKE<RepoInfo>("git_inspect", { path }),
  gitFileDiff: (path: string, file: string) =>
    __TAURI_INVOKE<Patch>("git_file_diff", { path, file }),
  gitInit: (path: string) => __TAURI_INVOKE<RepoInfo>("git_init", { path }),
  gitCommit: (input: CommitInput) =>
    __TAURI_INVOKE<string>("git_commit", { input }),
  aiStream: (
    requestId: string,
    config: ModelConfig,
    instruction: string,
    context: string,
    onEvent: Channel<StreamEvent>,
  ) =>
    __TAURI_INVOKE<string>("ai_stream", {
      requestId,
      config,
      instruction,
      context,
      onEvent,
    }),
  aiCancel: (requestId: string) =>
    __TAURI_INVOKE<null>("ai_cancel", { requestId }),
  agentRun: (
    requestId: string,
    config: ModelConfig,
    input: AgentInput,
    onEvent: Channel<AgentEvent>,
  ) =>
    __TAURI_INVOKE<AgentOutput>("agent_run", {
      requestId,
      config,
      input,
      onEvent,
    }),
  agentCancel: (requestId: string) =>
    __TAURI_INVOKE<null>("agent_cancel", { requestId }),
  credentialRead: (id: string, origin: string) =>
    __TAURI_INVOKE<string | null>("credential_read", { id, origin }),
  credentialWrite: (id: string, origin: string, key: string) =>
    __TAURI_INVOKE<null>("credential_write", { id, origin, key }),
  credentialRemove: (id: string, origin: string) =>
    __TAURI_INVOKE<null>("credential_remove", { id, origin }),
  mediaPick: (kind: string) =>
    __TAURI_INVOKE<{
      id: string;
      name: string;
      mime: string;
      size: number;
      width: number | null;
      height: number | null;
    } | null>("media_pick", { kind }),
  mediaImport: (bytes: number[], name: string) =>
    __TAURI_INVOKE<Asset>("media_import", { bytes, name }),
  mediaAsset: (id: string) => __TAURI_INVOKE<Asset>("media_asset", { id }),
  mediaPath: (id: string) => __TAURI_INVOKE<string>("media_path", { id }),
  mediaExport: (id: string) => __TAURI_INVOKE<boolean>("media_export", { id }),
  linkPreview: (url: string) =>
    __TAURI_INVOKE<LinkPreview>("link_preview", { url }),
  openExternal: (url: string) => __TAURI_INVOKE<null>("open_external", { url }),
  cardsList: () => __TAURI_INVOKE<Card[]>("cards_list"),
  cardSave: (card: Card) => __TAURI_INVOKE<Card>("card_save", { card }),
  captureOpen: (mode: string, monitor: number | null) =>
    __TAURI_INVOKE<null>("capture_open", { mode, monitor }),
  captureTake: () =>
    __TAURI_INVOKE<{
      id: string;
      mode: string;
      text: string;
      assetIds: string[];
      screenshot: ScreenCapture | null;
    } | null>("capture_take"),
  captureClipboard: () => __TAURI_INVOKE<CaptureSeed>("capture_clipboard"),
  captureScreens: () => __TAURI_INVOKE<Screen[]>("capture_screens"),
  captureRelease: (id: string) =>
    __TAURI_INVOKE<null>("capture_release", { id }),
  captureShortcutErrors: () =>
    __TAURI_INVOKE<string[]>("capture_shortcut_errors"),
  captureWindow: (action: string) =>
    __TAURI_INVOKE<null>("capture_window", { action }),
  captureInsert: (id: string) => __TAURI_INVOKE<null>("capture_insert", { id }),
  capturePendingInsert: () =>
    __TAURI_INVOKE<string | null>("capture_pending_insert"),
  capturePin: (id: string) => __TAURI_INVOKE<null>("capture_pin", { id }),
  capturePinned: () => __TAURI_INVOKE<string | null>("capture_pinned"),
  captureEnvironment: (language: string) =>
    __TAURI_INVOKE<CaptureEnvironment>("capture_environment", { language }),
  captureRequestAccess: () => __TAURI_INVOKE<boolean>("capture_request_access"),
};

/* Types */
export type AgentDraft = {
  title: string;
  markdown: string;
  summary: string;
};

export type AgentEvent =
  | { type: "started" }
  | { type: "thinking"; round: number }
  | { type: "tool"; name: string; detail: string; success: boolean };

export type AgentInput = {
  instruction: string;
  notes: AgentNote[];
  language: string;
};

export type AgentNote = {
  id: string;
  title: string;
  markdown: string;
};

export type AgentOutput = {
  status: AgentStatus;
  answer: string;
  draft: AgentDraft | null;
  readIds: string[];
  rounds: number;
};

export type AgentStatus = "complete" | "cancelled" | "limit";

/**  Stable IPC codes. Provider bodies and credentials must never enter these messages. */
export type AppError =
  | { code: "validation"; message: string }
  | { code: "storage"; message: string }
  | { code: "conflict"; message: string }
  | { code: "network"; message: string }
  | { code: "git"; message: string }
  | { code: "internal"; message: string };

export type Asset = {
  id: string;
  name: string;
  mime: string;
  size: number;
  width: number | null;
  height: number | null;
};

export type CaptureEnvironment = {
  platform: string;
  screenAccess: boolean;
  trayAvailable: boolean;
  shortcutErrors: string[];
};

export type CaptureSeed = {
  id: string;
  mode: string;
  text: string;
  assetIds: string[];
  screenshot: ScreenCapture | null;
};

/**
 *  Bounds relative to the captured display, in the display's coordinate units.
 *  Ordered front to back; no window titles or executable paths cross IPC.
 */
export type CaptureWindowBounds = {
  x: number;
  y: number;
  width: number;
  height: number;
};

export type Card = {
  id: string;
  title: string;
  body: string;
  assetIds: string[];
  sourceUrl: string;
  pinned: boolean;
  archived: boolean;
  createdAt: number;
  updatedAt: number;
  revision: number;
};

export type Change = {
  path: string;
  kind: string;
  staged: boolean;
};

export type Commit = {
  id: string;
  summary: string;
  author: string;
  time: number;
};

export type CommitInput = {
  path: string;
  files: string[];
  message: string;
  name: string;
  email: string;
  expectedHead: string;
};

export type Document = {
  id: string;
  title: string;
  markdown: string;
  updated: number;
};

export type Library = {
  revision: number;
  docs: Document[];
  location: string;
};

export type LinkPreview = {
  url: string;
  title: string;
  description: string;
  site: string;
  kind: string;
  thumbnail: Asset | null;
};

export type ModelConfig = {
  baseUrl: string;
  apiKey: string;
  model: string;
  protocol: string;
};

export type ModelList = {
  data: ModelSummary[];
  elapsedMs: number;
};

export type ModelSummary = {
  id: string;
};

export type ModelVerification = {
  elapsedMs: number;
  toolsSupported: boolean;
};

export type Patch = {
  text: string;
  truncated: boolean;
};

export type RepoInfo = {
  path: string;
  branch: string;
  head: string;
  changes: Change[];
  history: Commit[];
  truncated: boolean;
  authorName: string;
  authorEmail: string;
  state: string;
};

export type Screen = {
  id: number;
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  scale: number | null;
  primary: boolean;
};

export type ScreenCapture = {
  id: string;
  path: string;
  screen: Screen;
  windows?: CaptureWindowBounds[];
};

export type Snapshot = {
  id: number;
  title: string;
  markdown: string;
  saved: number;
};

export type StreamEvent = { type: "started" } | { type: "delta"; text: string };
